/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as QueueRouteImport } from './routes/queue'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiSitemapDotxmlRouteImport } from './routes/api/sitemap[.]xml'
import { Route as RegionUsernameIndexRouteImport } from './routes/$region.$username.index'
import { Route as ApiSitemapPageDotxmlRouteImport } from './routes/api/sitemap.$page[.]xml'
import { Route as ApiImagesSplatRouteImport } from './routes/api/images/$'
import { Route as RegionUsernameMatchesRouteImport } from './routes/$region.$username.matches'
import { Route as RegionUsernameMasteryRouteImport } from './routes/$region.$username.mastery'
import { Route as RegionUsernameDifferentRouteImport } from './routes/$region.$username.different'

const QueueRoute = QueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSitemapDotxmlRoute = ApiSitemapDotxmlRouteImport.update({
  id: '/api/sitemap.xml',
  path: '/api/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RegionUsernameIndexRoute = RegionUsernameIndexRouteImport.update({
  id: '/$region/$username/',
  path: '/$region/$username/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSitemapPageDotxmlRoute = ApiSitemapPageDotxmlRouteImport.update({
  id: '/api/sitemap/$page.xml',
  path: '/api/sitemap/$page.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiImagesSplatRoute = ApiImagesSplatRouteImport.update({
  id: '/api/images/$',
  path: '/api/images/$',
  getParentRoute: () => rootRouteImport,
} as any)
const RegionUsernameMatchesRoute = RegionUsernameMatchesRouteImport.update({
  id: '/$region/$username/matches',
  path: '/$region/$username/matches',
  getParentRoute: () => rootRouteImport,
} as any)
const RegionUsernameMasteryRoute = RegionUsernameMasteryRouteImport.update({
  id: '/$region/$username/mastery',
  path: '/$region/$username/mastery',
  getParentRoute: () => rootRouteImport,
} as any)
const RegionUsernameDifferentRoute = RegionUsernameDifferentRouteImport.update({
  id: '/$region/$username/different',
  path: '/$region/$username/different',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/queue': typeof QueueRoute
  '/api/sitemap.xml': typeof ApiSitemapDotxmlRoute
  '/$region/$username/different': typeof RegionUsernameDifferentRoute
  '/$region/$username/mastery': typeof RegionUsernameMasteryRoute
  '/$region/$username/matches': typeof RegionUsernameMatchesRoute
  '/api/images/$': typeof ApiImagesSplatRoute
  '/api/sitemap/$page.xml': typeof ApiSitemapPageDotxmlRoute
  '/$region/$username': typeof RegionUsernameIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/queue': typeof QueueRoute
  '/api/sitemap.xml': typeof ApiSitemapDotxmlRoute
  '/$region/$username/different': typeof RegionUsernameDifferentRoute
  '/$region/$username/mastery': typeof RegionUsernameMasteryRoute
  '/$region/$username/matches': typeof RegionUsernameMatchesRoute
  '/api/images/$': typeof ApiImagesSplatRoute
  '/api/sitemap/$page.xml': typeof ApiSitemapPageDotxmlRoute
  '/$region/$username': typeof RegionUsernameIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/queue': typeof QueueRoute
  '/api/sitemap.xml': typeof ApiSitemapDotxmlRoute
  '/$region/$username/different': typeof RegionUsernameDifferentRoute
  '/$region/$username/mastery': typeof RegionUsernameMasteryRoute
  '/$region/$username/matches': typeof RegionUsernameMatchesRoute
  '/api/images/$': typeof ApiImagesSplatRoute
  '/api/sitemap/$page.xml': typeof ApiSitemapPageDotxmlRoute
  '/$region/$username/': typeof RegionUsernameIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/queue'
    | '/api/sitemap.xml'
    | '/$region/$username/different'
    | '/$region/$username/mastery'
    | '/$region/$username/matches'
    | '/api/images/$'
    | '/api/sitemap/$page.xml'
    | '/$region/$username'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/queue'
    | '/api/sitemap.xml'
    | '/$region/$username/different'
    | '/$region/$username/mastery'
    | '/$region/$username/matches'
    | '/api/images/$'
    | '/api/sitemap/$page.xml'
    | '/$region/$username'
  id:
    | '__root__'
    | '/'
    | '/queue'
    | '/api/sitemap.xml'
    | '/$region/$username/different'
    | '/$region/$username/mastery'
    | '/$region/$username/matches'
    | '/api/images/$'
    | '/api/sitemap/$page.xml'
    | '/$region/$username/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  QueueRoute: typeof QueueRoute
  ApiSitemapDotxmlRoute: typeof ApiSitemapDotxmlRoute
  RegionUsernameDifferentRoute: typeof RegionUsernameDifferentRoute
  RegionUsernameMasteryRoute: typeof RegionUsernameMasteryRoute
  RegionUsernameMatchesRoute: typeof RegionUsernameMatchesRoute
  ApiImagesSplatRoute: typeof ApiImagesSplatRoute
  ApiSitemapPageDotxmlRoute: typeof ApiSitemapPageDotxmlRoute
  RegionUsernameIndexRoute: typeof RegionUsernameIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/queue': {
      id: '/queue'
      path: '/queue'
      fullPath: '/queue'
      preLoaderRoute: typeof QueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sitemap.xml': {
      id: '/api/sitemap.xml'
      path: '/api/sitemap.xml'
      fullPath: '/api/sitemap.xml'
      preLoaderRoute: typeof ApiSitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$region/$username/': {
      id: '/$region/$username/'
      path: '/$region/$username'
      fullPath: '/$region/$username'
      preLoaderRoute: typeof RegionUsernameIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sitemap/$page.xml': {
      id: '/api/sitemap/$page.xml'
      path: '/api/sitemap/$page.xml'
      fullPath: '/api/sitemap/$page.xml'
      preLoaderRoute: typeof ApiSitemapPageDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/images/$': {
      id: '/api/images/$'
      path: '/api/images/$'
      fullPath: '/api/images/$'
      preLoaderRoute: typeof ApiImagesSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$region/$username/matches': {
      id: '/$region/$username/matches'
      path: '/$region/$username/matches'
      fullPath: '/$region/$username/matches'
      preLoaderRoute: typeof RegionUsernameMatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$region/$username/mastery': {
      id: '/$region/$username/mastery'
      path: '/$region/$username/mastery'
      fullPath: '/$region/$username/mastery'
      preLoaderRoute: typeof RegionUsernameMasteryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$region/$username/different': {
      id: '/$region/$username/different'
      path: '/$region/$username/different'
      fullPath: '/$region/$username/different'
      preLoaderRoute: typeof RegionUsernameDifferentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  QueueRoute: QueueRoute,
  ApiSitemapDotxmlRoute: ApiSitemapDotxmlRoute,
  RegionUsernameDifferentRoute: RegionUsernameDifferentRoute,
  RegionUsernameMasteryRoute: RegionUsernameMasteryRoute,
  RegionUsernameMatchesRoute: RegionUsernameMatchesRoute,
  ApiImagesSplatRoute: ApiImagesSplatRoute,
  ApiSitemapPageDotxmlRoute: ApiSitemapPageDotxmlRoute,
  RegionUsernameIndexRoute: RegionUsernameIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
