/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RegionUsernameIndexRouteImport } from './routes/$region.$username.index'
import { Route as ApiImagesSplatRouteImport } from './routes/api/images/$'
import { Route as RegionUsernameMasteryRouteImport } from './routes/$region.$username.mastery'
import { Route as RegionUsernameDifferentRouteImport } from './routes/$region.$username.different'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegionUsernameIndexRoute = RegionUsernameIndexRouteImport.update({
  id: '/$region/$username/',
  path: '/$region/$username/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiImagesSplatRoute = ApiImagesSplatRouteImport.update({
  id: '/api/images/$',
  path: '/api/images/$',
  getParentRoute: () => rootRouteImport,
} as any)
const RegionUsernameMasteryRoute = RegionUsernameMasteryRouteImport.update({
  id: '/$region/$username/mastery',
  path: '/$region/$username/mastery',
  getParentRoute: () => rootRouteImport,
} as any)
const RegionUsernameDifferentRoute = RegionUsernameDifferentRouteImport.update({
  id: '/$region/$username/different',
  path: '/$region/$username/different',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$region/$username/different': typeof RegionUsernameDifferentRoute
  '/$region/$username/mastery': typeof RegionUsernameMasteryRoute
  '/api/images/$': typeof ApiImagesSplatRoute
  '/$region/$username': typeof RegionUsernameIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$region/$username/different': typeof RegionUsernameDifferentRoute
  '/$region/$username/mastery': typeof RegionUsernameMasteryRoute
  '/api/images/$': typeof ApiImagesSplatRoute
  '/$region/$username': typeof RegionUsernameIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$region/$username/different': typeof RegionUsernameDifferentRoute
  '/$region/$username/mastery': typeof RegionUsernameMasteryRoute
  '/api/images/$': typeof ApiImagesSplatRoute
  '/$region/$username/': typeof RegionUsernameIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$region/$username/different'
    | '/$region/$username/mastery'
    | '/api/images/$'
    | '/$region/$username'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$region/$username/different'
    | '/$region/$username/mastery'
    | '/api/images/$'
    | '/$region/$username'
  id:
    | '__root__'
    | '/'
    | '/$region/$username/different'
    | '/$region/$username/mastery'
    | '/api/images/$'
    | '/$region/$username/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RegionUsernameDifferentRoute: typeof RegionUsernameDifferentRoute
  RegionUsernameMasteryRoute: typeof RegionUsernameMasteryRoute
  ApiImagesSplatRoute: typeof ApiImagesSplatRoute
  RegionUsernameIndexRoute: typeof RegionUsernameIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$region/$username/': {
      id: '/$region/$username/'
      path: '/$region/$username'
      fullPath: '/$region/$username'
      preLoaderRoute: typeof RegionUsernameIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/images/$': {
      id: '/api/images/$'
      path: '/api/images/$'
      fullPath: '/api/images/$'
      preLoaderRoute: typeof ApiImagesSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$region/$username/mastery': {
      id: '/$region/$username/mastery'
      path: '/$region/$username/mastery'
      fullPath: '/$region/$username/mastery'
      preLoaderRoute: typeof RegionUsernameMasteryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$region/$username/different': {
      id: '/$region/$username/different'
      path: '/$region/$username/different'
      fullPath: '/$region/$username/different'
      preLoaderRoute: typeof RegionUsernameDifferentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RegionUsernameDifferentRoute: RegionUsernameDifferentRoute,
  RegionUsernameMasteryRoute: RegionUsernameMasteryRoute,
  ApiImagesSplatRoute: ApiImagesSplatRoute,
  RegionUsernameIndexRoute: RegionUsernameIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
