/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RegionUsernameRouteImport } from './routes/$region.$username'
import { Route as RegionUsernameMasteryRouteImport } from './routes/$region.$username.mastery'
import { Route as RegionUsernameDifferentRouteImport } from './routes/$region.$username.different'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegionUsernameRoute = RegionUsernameRouteImport.update({
  id: '/$region/$username',
  path: '/$region/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const RegionUsernameMasteryRoute = RegionUsernameMasteryRouteImport.update({
  id: '/mastery',
  path: '/mastery',
  getParentRoute: () => RegionUsernameRoute,
} as any)
const RegionUsernameDifferentRoute = RegionUsernameDifferentRouteImport.update({
  id: '/different',
  path: '/different',
  getParentRoute: () => RegionUsernameRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$region/$username': typeof RegionUsernameRouteWithChildren
  '/$region/$username/different': typeof RegionUsernameDifferentRoute
  '/$region/$username/mastery': typeof RegionUsernameMasteryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$region/$username': typeof RegionUsernameRouteWithChildren
  '/$region/$username/different': typeof RegionUsernameDifferentRoute
  '/$region/$username/mastery': typeof RegionUsernameMasteryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$region/$username': typeof RegionUsernameRouteWithChildren
  '/$region/$username/different': typeof RegionUsernameDifferentRoute
  '/$region/$username/mastery': typeof RegionUsernameMasteryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$region/$username'
    | '/$region/$username/different'
    | '/$region/$username/mastery'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$region/$username'
    | '/$region/$username/different'
    | '/$region/$username/mastery'
  id:
    | '__root__'
    | '/'
    | '/$region/$username'
    | '/$region/$username/different'
    | '/$region/$username/mastery'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RegionUsernameRoute: typeof RegionUsernameRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$region/$username': {
      id: '/$region/$username'
      path: '/$region/$username'
      fullPath: '/$region/$username'
      preLoaderRoute: typeof RegionUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$region/$username/mastery': {
      id: '/$region/$username/mastery'
      path: '/mastery'
      fullPath: '/$region/$username/mastery'
      preLoaderRoute: typeof RegionUsernameMasteryRouteImport
      parentRoute: typeof RegionUsernameRoute
    }
    '/$region/$username/different': {
      id: '/$region/$username/different'
      path: '/different'
      fullPath: '/$region/$username/different'
      preLoaderRoute: typeof RegionUsernameDifferentRouteImport
      parentRoute: typeof RegionUsernameRoute
    }
  }
}

interface RegionUsernameRouteChildren {
  RegionUsernameDifferentRoute: typeof RegionUsernameDifferentRoute
  RegionUsernameMasteryRoute: typeof RegionUsernameMasteryRoute
}

const RegionUsernameRouteChildren: RegionUsernameRouteChildren = {
  RegionUsernameDifferentRoute: RegionUsernameDifferentRoute,
  RegionUsernameMasteryRoute: RegionUsernameMasteryRoute,
}

const RegionUsernameRouteWithChildren = RegionUsernameRoute._addFileChildren(
  RegionUsernameRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RegionUsernameRoute: RegionUsernameRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
