/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RegionUsernameIndexRouteImport } from './routes/$region.$username.index'
import { Route as RegionUsernameTestRouteImport } from './routes/$region.$username.test'
import { Route as RegionUsernameMasteryRouteImport } from './routes/$region.$username.mastery'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegionUsernameIndexRoute = RegionUsernameIndexRouteImport.update({
  id: '/$region/$username/',
  path: '/$region/$username/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegionUsernameTestRoute = RegionUsernameTestRouteImport.update({
  id: '/$region/$username/test',
  path: '/$region/$username/test',
  getParentRoute: () => rootRouteImport,
} as any)
const RegionUsernameMasteryRoute = RegionUsernameMasteryRouteImport.update({
  id: '/$region/$username/mastery',
  path: '/$region/$username/mastery',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$region/$username/mastery': typeof RegionUsernameMasteryRoute
  '/$region/$username/test': typeof RegionUsernameTestRoute
  '/$region/$username': typeof RegionUsernameIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$region/$username/mastery': typeof RegionUsernameMasteryRoute
  '/$region/$username/test': typeof RegionUsernameTestRoute
  '/$region/$username': typeof RegionUsernameIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$region/$username/mastery': typeof RegionUsernameMasteryRoute
  '/$region/$username/test': typeof RegionUsernameTestRoute
  '/$region/$username/': typeof RegionUsernameIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$region/$username/mastery'
    | '/$region/$username/test'
    | '/$region/$username'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$region/$username/mastery'
    | '/$region/$username/test'
    | '/$region/$username'
  id:
    | '__root__'
    | '/'
    | '/$region/$username/mastery'
    | '/$region/$username/test'
    | '/$region/$username/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RegionUsernameMasteryRoute: typeof RegionUsernameMasteryRoute
  RegionUsernameTestRoute: typeof RegionUsernameTestRoute
  RegionUsernameIndexRoute: typeof RegionUsernameIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$region/$username/': {
      id: '/$region/$username/'
      path: '/$region/$username'
      fullPath: '/$region/$username'
      preLoaderRoute: typeof RegionUsernameIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$region/$username/test': {
      id: '/$region/$username/test'
      path: '/$region/$username/test'
      fullPath: '/$region/$username/test'
      preLoaderRoute: typeof RegionUsernameTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$region/$username/mastery': {
      id: '/$region/$username/mastery'
      path: '/$region/$username/mastery'
      fullPath: '/$region/$username/mastery'
      preLoaderRoute: typeof RegionUsernameMasteryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RegionUsernameMasteryRoute: RegionUsernameMasteryRoute,
  RegionUsernameTestRoute: RegionUsernameTestRoute,
  RegionUsernameIndexRoute: RegionUsernameIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
